#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2013-2018 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

URBACKUP_SERVER_CONFIG="/etc/default/urbackupsrv"
XPATH="/config/services/urbackup-server"

log_level=$(omv_config_get "${XPATH}/loglevel")
port=$(omv_config_get "${XPATH}/port")
webport=$(omv_config_get "${XPATH}/webport")
if [[ $(omv_config_get "${XPATH}/runasroot") -eq 1 ]]; then
    runasroot="USER=root"
else
    runasroot=""
fi

# Create urbackup-server defaults file
cat <<EOF > ${URBACKUP_SERVER_CONFIG}
# Defaults for urbackupsrv initscript
# sourced by /etc/init.d/urbackupsrv and /lib/systemd/system/urbackup-server.service
# installed at /etc/default/urbackupsrv by the maintainer scripts

#
# This is parsed as a key=value file
#

#Port for FastCGI requests
FASTCGI_PORT=${port}

#Enable internal HTTP server
HTTP_SERVER="true"

#Port for the web interface
#(if internal HTTP server is enabled)
HTTP_PORT=${webport}

#log file name
LOGFILE="/var/log/urbackup.log"

#Either debug,warn,info or error
LOGLEVEL="${log_level}"

#Temporary file directory
# -- this may get very large depending on the advanced settings
DAEMON_TMPDIR="/tmp"

#Tmp file directory for sqlite temporary tables.
#You might want to put the databases on another filesystem than the other temporary files.
#Default is the same as DAEMON_TMPDIR
SQLITE_TMPDIR=""

#Interfaces from which to send broadcasts. (Default: all).
#Comma separated -- e.g. "eth0,eth1"
BROADCAST_INTERFACES=""
${runasroot}
${extraoptions}
EOF

exit 0